name: CI-Test

on: [push, pull_request]

jobs:
  lint:
    name: Check Code Style - FLAKE8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          # These packages are installed in the base environment but may be older
          # versions. Explicitly upgrade them because they often create
          # installation problems if out of date.
          python -m pip install --upgrade pip setuptools numpy
          pip install flake8

      - name: Run flake8
        run: |
          flake8 --max-line-length=115
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          set -vxeuo pipefail
          bash ./scripts/install-deps.sh

      - name: Test with pytest
        run: |
          set -vxeuo pipefail
          bash ./scripts/run-tests.sh
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: false

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          set -vxeuo pipefail
          bash ./scripts/install-deps.sh

      - name: Build Docs
        run: |
          set -vxeuo pipefail
          bash ./scripts/build-docs.sh
